# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "im-upload"
client_id = "4ce4e0f5fe810a889e4c7511e043972c"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "squirrels-and-squirrels.myshopify.com"
